### ISSUE TITLE
Testing the MusicXML to Mnx Converter 

### ISSUE THREAD

**Issue by mogenslundholm** [w3c/mnxconverter#2]
Produced some test cases for the converter. The converter works really good. I encountered a few problems:

    python convert.py "a.musicxml": (When a measure has whole rest)
    
    File ".....\mnxconverter-master-2020-07-07\mnxconverter\mnx_common.py", line 239, in microformat_duration
        if frac > 1:
    TypeError: '>' not supported between instances of 'NoneType' and 'int'`
   
    python convert.py "schbavmasample.musicxml": (good old MusicXML-test file - I can't see intersection)
    
        raise NotImplementedError("Beams intersecting tuplets aren't yet `supported.")`
    NotImplementedError: Beams intersecting tuplets aren't yet supported.

As expected - Turkish music is not allowed:

    python convert.py .\saba--sazsemaisi--aksaksemai----neyzen_aziz_dede.musicxml 
      File ".....\mnxconverter\musicxml.py", line 612, in parse_pitch

        raise NotationDataError('Invalid <alter> for <pitch>.')
    mnxconverter.musicxml.NotationDataError: Invalid <alter> for <pitch>.

Attach test files a.musicxml and schbavmasample.musicxml

[a.zip](https://github.com/w3c/mnxconverter/files/5101888/a.zip)
[SchbAvMaSample.zip](https://github.com/w3c/mnxconverter/files/5101633/SchbAvMaSample.zip)

PS: Working on a MNX to MIDI converter - very "alpha" of cause but .... 
My main focus is performance. With MusicXML I used a state machine. Now I include the context in the symbols, but
this might lead to a very big number of symbols - depending on how MNX develops. Maybe too many symbols will appear. Just want to see if this is possible.
(This pre-alpha MNX to MIDI converter: https://programfabriken.com/MnxToMidi.zip)

**Comment by adrianholovaty** [comment]
@mogenslundholm Thanks for making these test cases! Will investigate...

**Comment by adrianholovaty** [comment]
I've improved the importer to deal with the "a.musicxml" file — thanks @mogenslundholm! See commit 17e47a743.

**Comment by adrianholovaty** [comment]
I've improved the converter to deal with the "SchbAvMaSample" file — thanks @mogenslundholm! See commit 4df6ebd40.

Marking this as closed now, as the converter no longer fails on the two uploaded examples. I know the issue also mentioned `Invalid <alter> for <pitch>.` (for Turkish music), but that's still not well defined within MNX for now, so I'm planning to wait for the MNX spec first before implementing in mnxconverter.

Thanks again for the test cases!

**Comment by mogenslundholm** [comment]
Sorry that I have never programmed in Python and cannot see why the file y.musicxml gives an error:

    python convert.py Y.musicxml
    ....
    
     in write_event
        event_el.attrib['value'] = microformat_duration(event.duration)
      File "C:\Users\Mogens Lundholm\Desktop\MNX-test\mnxconverter-master-2020-08-26\mnxconverter\mnx_common.py", 
                              line 245, in microformat_duration
        raise ValueError(f'Invalid duration fraction {frac}')
    ValueError: Invalid duration fraction 3/4

[Y.zip](https://github.com/w3c/mnxconverter/files/5129869/Y.zip)

PS:  The file y.musicxml  is excerpt from a song "Skye_Boat_Song". Now it gets longer in the file (After your correction). 
But generally: How do we handle copyright and so? So far I made only an excerpt from the song.

**Comment by adrianholovaty** [comment]
@mogenslundholm Thanks, I'll investigate. For the copyright concern, I think it's good to limit the examples to only excerpts that demonstrate a particular problem. If you have any doubt, please feel free to email files privately to me. When commiting code to the repository (such as our unit tests), I always make sure to make the music generic (not copyrighted).
