### ISSUE TITLE
Time signatures

### ISSUE THREAD

**Issue by mogenslundholm** [w3c/mnxconverter#5]
Do we need to handle such time signatures?

![image](https://user-images.githubusercontent.com/3636047/92601246-df210000-f2ac-11ea-90f1-d125b4e19a11.png)

I think this is from The Lilypond test suite: _11c-timesignatures-compoundsimple.musicxml_

[11c-TimeSignatures-CompoundSimple.zip](https://github.com/w3c/mnxconverter/files/5195289/11c-TimeSignatures-CompoundSimple.zip)

**Comment by adrianholovaty** [comment]
Marking this as closed, since this is more of an MNX thing than an mnxconverter thing. See this issue in the (separate) MNX repo: https://github.com/w3c/mnx/issues/254
