### ISSUE TITLE
Comment on the <beam>-solution of 2021-01-05

### ISSUE THREAD

**Issue by mogenslundholm** [w3c/mnxconverter#8]
Comments on the 2021.01.05 files:

1. Not fond of the nested &lt;beam&gt; - solution. Creating xml-symbol-chain like:
   &lt;?xml&gt;&lt;mnx&gt;&lt;part&gt;&lt;measure&gt;&lt;sequence&gt;&lt;beams&gt;&lt;beam&gt;&lt;beam&gt;&lt;beam-hook&gt;...
   or
   &lt;?xml&gt;&lt;mnx&gt;&lt;part&gt;&lt;measure&gt;&lt;sequence&gt;&lt;beams&gt;&lt;beam&gt;&lt;beam&gt;&lt;beam&gt; ...

   I would prefer something like:

   &lt;beam level="2" events="ev11 ev12"/&gt;

   (And the nested beam-solution is not a good solution for my parser so ...)

2. How will the note-id's affect performance and how big tables are needed?

3. Sanity: 
The number of beams and the note length are related: One beams = 1/8, Two beams = 1/16.
How to assure the sanity? Once you specify a beam - isn't the number of beams determined to just fit the note length?

Example: Calling the MusicXML-converter gives this error message

![image](https://user-images.githubusercontent.com/3636047/103869499-ad893b80-50ca-11eb-848f-475fd714ecde.png)

`python convert.py Hooks.musicxml .....`
`mnxconverter.musicxml.NotationDataError: Got <beam number="3"> outside of <beam
number="2">`

**Comment by mogenslundholm** [comment]
Would prefer &lt;beam&gt; to only define the structure and parameters to define the type:

`<beam hooks="right" tremolos="2" level="2" events="ev12 ev13"/`

The idea is that for a program where beams are not relevant, there is no need to parse hooks.

**Comment by adrianholovaty** [comment]
This is more of an MNX matter (not the mnxconverter), and the encoding of beams has changed since we migrated to JSON. Marking as closed.
